### ISSUE TITLE
Crash when Wyrmwood saplings tries to grow near snow layer?

### ISSUE THREAD

**Issue by LTCatt** [superfluke/enderoni#19]
[crash-2020-03-31_20.03.58-server.txt](https://github.com/superfluke/enderoni/files/4408953/crash-2020-03-31_20.03.58-server.txt)
Minecraft 1.12.2, Stygian 1.0.4.
Seems to be a crash caused by random growth event. I put the sapling on the endstone near snow, and after a while, it crashed.

**Comment by Krutoy242** [comment]
Same problem, but with another blocks
```java

java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=variant, clazz=class biomesoplenty.api.enums.BOPPlants, values=[shortgrass, mediumgrass, bush, sprout, poisonivy, berrybush, shrub, wheatgrass, dampgrass, koru, cloverpatch, leafpile, deadleafpile, deadgrass, desertgrass, desertsprouts]} as it does not exist in BlockStateContainer{block=minecraft:grass, properties=[snowy]}
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:209)
	at biomesoplenty.common.block.BlockBOPPlant.func_176200_f(BlockBOPPlant.java:288)
	at fluke.stygian.world.feature.WorldGenEnderCanopy.isValidGenLocation(WorldGenEnderCanopy.java:58)
	at fluke.stygian.world.feature.WorldGenEnderCanopy.func_180709_b(WorldGenEnderCanopy.java:39)
	at fluke.stygian.block.BlockEndCanopySapling.generateTree(BlockEndCanopySapling.java:81)
	at fluke.stygian.block.BlockEndCanopySapling.grow(BlockEndCanopySapling.java:71)
	at fluke.stygian.block.BlockEndCanopySapling.func_180650_b(BlockEndCanopySapling.java:58)
	at net.minecraft.block.Block.func_180645_a(Block.java:508)
```

**Comment by MagmaSlime123** [comment]
I doubt this mod will ever be active. Unless you're willing to continue this mod, then its dead.

**Comment by quentin452** [comment]
The pull request 21 is merged into my fork , https://legacy.curseforge.com/minecraft/mc-mods/stygian-end-continuation/ so the issue should be fixed

**Comment by Krutoy242** [comment]
> The pull request 21 is merged into my fork , https://legacy.curseforge.com/minecraft/mc-mods/stygian-end-continuation/ so the issue should be fixed

Thanks for the info!
